[2025-10-09T04:51:33.324+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: order_generator.load_orders scheduled__2025-10-08T23:00:00+00:00 [queued]>
[2025-10-09T04:51:33.355+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: order_generator.load_orders scheduled__2025-10-08T23:00:00+00:00 [queued]>
[2025-10-09T04:51:33.357+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:51:33.362+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:51:33.370+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:51:33.398+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_orders> on 2025-10-08 23:00:00+00:00
[2025-10-09T04:51:33.423+0000] {standard_task_runner.py:55} INFO - Started process 2558 to run task
[2025-10-09T04:51:33.428+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'order_generator', 'load_orders', 'scheduled__2025-10-08T23:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/order_loader_dag.py', '--cfg-path', '/tmp/tmp3qtwvf32']
[2025-10-09T04:51:33.431+0000] {standard_task_runner.py:83} INFO - Job 152: Subtask load_orders
[2025-10-09T04:51:33.575+0000] {task_command.py:389} INFO - Running <TaskInstance: order_generator.load_orders scheduled__2025-10-08T23:00:00+00:00 [running]> on host 81fbc710bbce
[2025-10-09T04:51:33.713+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=order_generator
AIRFLOW_CTX_TASK_ID=load_orders
AIRFLOW_CTX_EXECUTION_DATE=2025-10-08T23:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-08T23:00:00+00:00
[2025-10-09T04:51:33.769+0000] {logging_mixin.py:137} INFO - Successfully loaded data to orders
[2025-10-09T04:51:34.089+0000] {logging_mixin.py:137} INFO - Successfully loaded data to order_items
[2025-10-09T04:51:34.090+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:51:34.104+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=order_generator, task_id=load_orders, execution_date=20251008T230000, start_date=20251009T045133, end_date=20251009T045134
[2025-10-09T04:51:34.129+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:51:34.151+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
